<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Presentation.aspx.cs" Inherits="mlwlt_web_test.Presentation" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head id="Head1" runat="server">
    <meta charset="utf-8">
    <meta name="viewport" content="target-densitydpi=device-dpi, width=device-width, initial-scale=1.0, maximum-scale=1">
    <meta name="description" content="MLW-LT Testing Site (XLIFF/MT service)">
    <meta name="author" content="Milan Karásek, Moravia">
    <meta name="keywords" content="MLW-LT, Machine Translation, MT, XLIFF, Web service">
    <link href="css/modern.css" rel="stylesheet">
    <link href="css/modern-responsive.css" rel="stylesheet">
    <link href="css/site.css" rel="stylesheet" type="text/css">
    <link href="js/google-code-prettify/prettify.css" rel="stylesheet" type="text/css">

    <script type="text/javascript" src="js/assets/jquery-1.9.0.min.js"></script>
    <script type="text/javascript" src="js/assets/jquery.mousewheel.min.js"></script>

    <script type="text/javascript" src="js/modern/dropdown.js"></script>
    <script type="text/javascript" src="js/modern/accordion.js"></script>
    <script type="text/javascript" src="js/modern/buttonset.js"></script>
    <script type="text/javascript" src="js/modern/carousel.js"></script>
    <script type="text/javascript" src="js/modern/input-control.js"></script>
    <script type="text/javascript" src="js/modern/pagecontrol.js"></script>
    <script type="text/javascript" src="js/modern/rating.js"></script>
    <script type="text/javascript" src="js/modern/slider.js"></script>
    <script type="text/javascript" src="js/modern/tile-slider.js"></script>
    <script type="text/javascript" src="js/modern/tile-drag.js"></script>

    <title>MLW-LT Testing Site (XLIFF/MT service)</title>
    <style>
        html {overflow-y: scroll;}
        span.catname {font-family: Courier New;}
        span.highlight {background-color: #FEE78B;}
        ul.presentbullets li {margin: 15px 0 15px 10px;}
        ul.presentbullets li b {margin: 0 0 0 20px;}
        pre {margin-left:20px;}
    </style>
</head>
<body class="modern-ui" onload="prettyPrint()">


<div class="page">

<!--#include file="Header.htm"-->

    <div class="page-region">
        <div class="page-region-content">
            <h1>MLW-LT</h1>
            <h2>XLIFF/MT Round-Tripping</h2>
        
            <p>
                Demonstration, MLW Workshop, Rome, Luxembourg Mar 12.-15. 2013
            </p>
            <p>
                Test site with XLIFF/MT Round-Trip web service is
                <a href="http://80.65.176.168/mlwlt-web-test/" target="_blank">available</a>.
            </p>

            <ul class="presentbullets">
                <li>Implemented as a part of Solas workflow (Web-service based with it's <a href="http://80.65.176.168/mlwlt-service-xliff-mt/mlwlt-service.asmx?WSDL" target="_blank">WSDL</a>)</li>
                <li>XLIFF in, XLIFF out</li>
                <li>Processed ITS 2.0 mapped into XLIFF</li>
                <li>Consumes data categories:
                    <span class="catname">Translate</span>, 
                    <span class="catname">Domain</span> and
                    <span class="catname">Text Analysis</span>. 
                    <li>Generates metadata for data categories:
                    <span class="catname">Provenance</span> and
                    <span class="catname">MT Confidence</span></li>
                
                    <br/>&nbsp;<br/>
                    <b>Translate</b>
<div class="span8">
<pre style="background:#fff;color:#000">    <span style="color:#1c02ff">&lt;<span style="font-weight:700">trans-unit</span> <span style="font-style:italic">id</span>=<span style="color:#d80800">"#4"</span>></span>
        <span style="color:#1c02ff">&lt;<span style="font-weight:700">source</span> <span style="font-style:italic">xml</span>:lang=<span style="color:#d80800">"English"</span>></span>
            The first 'Classic' writer was Aulus Gellius a 2nd-century Roman writer who 
            in the miscellany Noctes Atticae (19  8  15) refers to a writer as a
            <span class="highlight"><span style="color:#1c02ff">&lt;<span style="font-weight:700">mrk</span> <span style="font-style:italic">mtype</span>=<span style="color:#d80800">"protected"</span>></span>Classicus scriptor  non proletarius<span style="color:#1c02ff">&lt;/<span style="font-weight:700">mrk</span>></span></span> 
            ('A distinguished  not a commonplace writer').
        <span style="color:#1c02ff">&lt;/<span style="font-weight:700">source</span>></span>
    <span style="color:#1c02ff">&lt;/<span style="font-weight:700">trans-unit</span>></span>
</pre> <!-- Generated by http://markup.su/highlighter/ -->
</div>

                    <br/>&nbsp;<br/>
                    <b>Domain</b>

<div class="span8">
<pre style="background:#fff;color:#000">    <span style="color:#1c02ff">&lt;<span style="font-weight:700">trans-unit</span> <span style="font-style:italic">id</span>=<span style="color:#d80800">"#1"</span> <span class="highlight"><span style="font-style:italic">itsx</span>:domain=<span style="color:#d80800">"classical-studies"</span></span>></span>
        <span style="color:#1c02ff">&lt;<span style="font-weight:700">source</span> <span style="font-style:italic">xml</span>:lang=<span style="color:#d80800">"English"</span>></span>Classical Studies<span style="color:#1c02ff">&lt;/<span style="font-weight:700">source</span>></span>
    <span style="color:#1c02ff">&lt;/<span style="font-weight:700">trans-unit</span>></span>
</pre>
</div>


                    <br/>&nbsp;<br/>
                    <b>Text Analysis</b>



<div class="span10">

<pre style="background:#fff;color:#000"><span style="color:#1c02ff">&lt;<span style="font-weight:700">trans-unit</span> <span style="font-style:italic">id</span>=<span style="color:#d80800">"#3"</span> <span style="font-style:italic">itsx</span>:domain=<span style="color:#d80800">"ITS-Example"</span>></span>
    <span style="color:#1c02ff">&lt;<span style="font-weight:700">source</span> <span style="font-style:italic">xml</span>:lang=<span style="color:#d80800">"en-us"</span>></span>
        From the canyons of 
        <span class="highlight"><span style="color:#1c02ff">&lt;<span style="font-weight:700">mrk</span> <span style="font-style:italic">mtype</span>=<span style="color:#d80800">"x-its"</span> <span style="font-style:italic">its</span>:taConfidence=<span style="color:#d80800">"0.7"</span> <span style="font-style:italic">its</span>:taClassRef=<span style="color:#d80800">"http://nerd.eurecom.fr/ontology#Place"</span> 
          <span style="font-style:italic">its</span>:taIdentRef=<span style="color:#d80800">"http://dbpedia.org/resource/Arizona"</span>></span>Arizona<span style="color:#1c02ff">&lt;/<span style="font-weight:700">mrk</span>></span></span>, 
        to the Khmer temples deep in the jungle; from the tropical beaches of Queensland to the glaciers of 
        <span class="highlight"><span style="color:#1c02ff">&lt;<span style="font-weight:700">mrk</span> <span style="font-style:italic">mtype</span>=<span style="color:#d80800">"x-its"</span> <span style="font-style:italic">its</span>:taConfidence=<span style="color:#d80800">"0.7"</span> <span style="font-style:italic">its</span>:taClassRef=<span style="color:#d80800">"http://nerd.eurecom.fr/ontology#Place"</span> 
          <span style="font-style:italic">its</span>:taIdentRef=<span style="color:#d80800">"http://dbpedia.org/resource/Antarctica"</span>></span>Antarctica<span style="color:#1c02ff">&lt;/<span style="font-weight:700">mrk</span>></span></span>; 
        or from the wild savanna of 
        <span class="highlight"><span style="color:#1c02ff">&lt;<span style="font-weight:700">mrk</span> <span style="font-style:italic">mtype</span>=<span style="color:#d80800">"x-its"</span> <span style="font-style:italic">its</span>:taConfidence=<span style="color:#d80800">"0.7"</span> <span style="font-style:italic">its</span>:taClassRef=<span style="color:#d80800">"http://nerd.eurecom.fr/ontology#Place"</span> 
          <span style="font-style:italic">its</span>:taIdentRef=<span style="color:#d80800">"http://dbpedia.org/resource/Africa"</span>></span>Africa<span style="color:#1c02ff">&lt;/<span style="font-weight:700">mrk</span>></span></span>
        to mysterious castles in the forests of Bohemia, our offer takes you in some of the most amazing 
        places on our planet.
    <span style="color:#1c02ff">&lt;/<span style="font-weight:700">source</span>></span>
<span style="color:#1c02ff">&lt;/<span style="font-weight:700">trans-unit</span>></span>
</pre>

</div>
                
                    <br/>&nbsp;<br/>
                    <br/>&nbsp;<br/>

                </li>

                <li>Output: XLIFF File enhanced by MT:
                
                    <br/>&nbsp;<br/>
                    <b>Translate (output)</b>
                
<div class="span10">
<pre style="background:#fff;color:#000"><span style="color:#1c02ff">&lt;<span style="font-weight:700">trans-unit</span> <span style="font-style:italic">id</span>=<span style="color:#d80800">"#4"</span>></span>
    <span style="color:#1c02ff">&lt;<span style="font-weight:700">source</span> <span style="font-style:italic">xml</span>:lang=<span style="color:#d80800">"English"</span>></span>
        The first 'Classic' writer was Aulus Gellius a 2nd-century Roman writer 
        who in the miscellany Noctes Atticae (19 8 15) refers to a writer as 
        a <span style="color:#1c02ff">&lt;<span style="font-weight:700">mrk</span> <span style="font-style:italic">mtype</span>=<span style="color:#d80800">"protected"</span>></span>Classicus scriptor non proletarius<span style="color:#1c02ff">&lt;/<span style="font-weight:700">mrk</span>></span>
        ('A distinguished not a commonplace writer'). 
    <span style="color:#1c02ff">&lt;/<span style="font-weight:700">source</span>></span>
    <span style="color:#1c02ff">&lt;<span style="font-weight:700">alt-trans</span> <span style="font-style:italic">match-quality</span>=<span style="color:#d80800">"0.749"</span> <span style="font-style:italic">origin</span>=<span style="color:#d80800">"MT"</span>></span>
        <span style="color:#1c02ff">&lt;<span style="font-weight:700">target</span> <span style="font-style:italic">xml</span>:lang=<span style="color:#d80800">"Spanish"</span> <span style="font-style:italic">its</span>:provenanceRecordsRef=<span style="color:#d80800">"#pr3"</span>></span>
            La primera 'Classic' Writer era aulus gellius un 2nd-century Roman Writer 
            que en la miscellany noctes atticae (19 8 15) refers a una Writer como un
            <span class="highlight"><span style="color:#1c02ff">&lt;<span style="font-weight:700">mrk</span> <span style="font-style:italic">mtype</span>=<span style="color:#d80800">"protected"</span>></span>Classicus scriptor non proletarius<span style="color:#1c02ff">&lt;/<span style="font-weight:700">mrk</span>></span></span>
            ('un Distinguished no una moneda corriente Writer').
        <span style="color:#1c02ff">&lt;/<span style="font-weight:700">target</span>></span>
    <span style="color:#1c02ff">&lt;/<span style="font-weight:700">alt-trans</span>></span>
<span style="color:#1c02ff">&lt;/<span style="font-weight:700">trans-unit</span>></span>
</pre>
</div>
                

                    <br/>&nbsp;<br/>
                    <b>Text Analysis (output)</b> In case of Text analysis metadata presence, translation is taken from the referenced site instead of MT.
                    
<div class="span10">

<pre style="background:#fff;color:#000"><span style="color:#1c02ff">&lt;<span style="font-weight:700">trans-unit</span> <span style="font-style:italic">id</span>=<span style="color:#d80800">"#3"</span> <span style="font-style:italic">itsx</span>:domain=<span style="color:#d80800">"ITS-Example"</span>></span>
    <span style="color:#1c02ff">&lt;<span style="font-weight:700">source</span> <span style="font-style:italic">xml</span>:lang=<span style="color:#d80800">"en-us"</span>></span>
        From the canyons of 
        <span style="color:#1c02ff">&lt;<span style="font-weight:700">mrk</span> <span style="font-style:italic">mtype</span>=<span style="color:#d80800">"x-its"</span> <span style="font-style:italic">its</span>:taConfidence=<span style="color:#d80800">"0.7"</span> <span style="font-style:italic">its</span>:taClassRef=<span style="color:#d80800">"http://nerd.eurecom.fr/ontology#Place"</span> 
          <span style="font-style:italic">its</span>:taIdentRef=<span style="color:#d80800">"http://dbpedia.org/resource/Arizona"</span>></span>Arizona<span style="color:#1c02ff">&lt;/<span style="font-weight:700">mrk</span>></span>, 
        to the Khmer temples deep in the jungle; from the tropical beaches of Queensland to the glaciers of 
        <span style="color:#1c02ff">&lt;<span style="font-weight:700">mrk</span> <span style="font-style:italic">mtype</span>=<span style="color:#d80800">"x-its"</span> <span style="font-style:italic">its</span>:taConfidence=<span style="color:#d80800">"0.7"</span> <span style="font-style:italic">its</span>:taClassRef=<span style="color:#d80800">"http://nerd.eurecom.fr/ontology#Place"</span> 
          <span style="font-style:italic">its</span>:taIdentRef=<span style="color:#d80800">"http://dbpedia.org/resource/Antarctica"</span>></span>Antarctica<span style="color:#1c02ff">&lt;/<span style="font-weight:700">mrk</span>></span>; 
        or from the wild savanna of 
        <span style="color:#1c02ff">&lt;<span style="font-weight:700">mrk</span> <span style="font-style:italic">mtype</span>=<span style="color:#d80800">"x-its"</span> <span style="font-style:italic">its</span>:taConfidence=<span style="color:#d80800">"0.7"</span> <span style="font-style:italic">its</span>:taClassRef=<span style="color:#d80800">"http://nerd.eurecom.fr/ontology#Place"</span> 
          <span style="font-style:italic">its</span>:taIdentRef=<span style="color:#d80800">"http://dbpedia.org/resource/Africa"</span>></span>Africa<span style="color:#1c02ff">&lt;/<span style="font-weight:700">mrk</span>></span>
        to mysterious castles in the forests of Bohemia, our offer takes you in some of the most amazing 
        places on our planet.
    <span style="color:#1c02ff">&lt;/<span style="font-weight:700">source</span>></span>
    <span style="color:#1c02ff">&lt;<span style="font-weight:700">alt-trans</span> <span style="font-style:italic">mid</span>=<span style="color:#d80800">"0"</span> <span style="font-style:italic">match-quality</span>=<span style="color:#d80800">"0.749"</span> <span style="font-style:italic">origin</span>=<span style="color:#d80800">"MT"</span>></span>
        <span style="color:#1c02ff">&lt;<span style="font-weight:700">source</span> <span style="font-style:italic">xml</span>:lang=<span style="color:#d80800">"en-us"</span>></span>
            From the canyons of ...
        <span style="color:#1c02ff">&lt;/<span style="font-weight:700">source</span>></span>
        <span style="color:#1c02ff">&lt;<span style="font-weight:700">target</span> <span style="font-style:italic">xml</span>:lang=<span style="color:#d80800">"fr-fr"</span> <span style="font-style:italic">its</span>:provenanceRecordsRef=<span style="color:#d80800">"#pr3"</span>></span>
            Des canyons de 
            <span style="color:#1c02ff">&lt;<span style="font-weight:700">mrk</span> <span style="font-style:italic">mtype</span>=<span style="color:#d80800">"x-its"</span> <span style="font-style:italic">its</span>:taConfidence=<span style="color:#d80800">"0.7"</span> <span style="font-style:italic">its</span>:taClassRef=<span style="color:#d80800">"http://nerd.eurecom.fr/ontology#Place"</span> 
              <span style="font-style:italic">its</span>:taIdentRef=<span style="color:#d80800">"http://dbpedia.org/resource/Arizona"</span>></span><span class="highlight">Arizona</span><span style="color:#1c02ff">&lt;/<span style="font-weight:700">mrk</span>></span>,
            à la Khmers temples profonde dans la jungle tropicale; des plages du Queensland à les glaciers de 
            <span style="color:#1c02ff">&lt;<span style="font-weight:700">mrk</span> <span style="font-style:italic">mtype</span>=<span style="color:#d80800">"x-its"</span> <span style="font-style:italic">its</span>:taConfidence=<span style="color:#d80800">"0.7"</span> <span style="font-style:italic">its</span>:taClassRef=<span style="color:#d80800">"http://nerd.eurecom.fr/ontology#Place"</span> 
              <span style="font-style:italic">its</span>:taIdentRef=<span style="color:#d80800">"http://dbpedia.org/resource/Antarctica"</span>></span><span class="highlight">Antarctique</span><span style="color:#1c02ff">&lt;/<span style="font-weight:700">mrk</span>></span> 
            à la vie sauvage de savanna 
            <span style="color:#1c02ff">&lt;<span style="font-weight:700">mrk</span> <span style="font-style:italic">mtype</span>=<span style="color:#d80800">"x-its"</span> <span style="font-style:italic">its</span>:taConfidence=<span style="color:#d80800">"0.7"</span> <span style="font-style:italic">its</span>:taClassRef=<span style="color:#d80800">"http://nerd.eurecom.fr/ontology#Place"</span> 
              <span style="font-style:italic">its</span>:taIdentRef=<span style="color:#d80800">"http://dbpedia.org/resource/Africa"</span>></span><span class="highlight">Afrique</span><span style="color:#1c02ff">&lt;/<span style="font-weight:700">mrk</span>></span> 
            de mystérieux châteaux dans les forêts de la Bohème, notre offre vous prenne dans certains 
            endroits les plus sensationnels sur notre planète.
        <span style="color:#1c02ff">&lt;/<span style="font-weight:700">target</span>></span>
    <span style="color:#1c02ff">&lt;/<span style="font-weight:700">alt-trans</span>></span>
<span style="color:#1c02ff">&lt;/<span style="font-weight:700">trans-unit</span>></span>
</pre>

</div>

                    <br/>&nbsp;<br/>
                    <b>MT Confidence (output)</b>

<div class="span10">
<pre style="background:#fff;color:#000"><span style="color:#1c02ff">&lt;<span style="font-weight:700">trans-unit</span> <span style="font-style:italic">id</span>=<span style="color:#d80800">"#4"</span>></span>
    <span style="color:#1c02ff">&lt;<span style="font-weight:700">source</span> <span style="font-style:italic">xml</span>:lang=<span style="color:#d80800">"English"</span>></span>
        The first 'Classic' writer was Aulus Gellius a 2nd-century Roman writer 
        who in the miscellany Noctes Atticae (19 8 15) refers to a writer as 
        a <span style="color:#1c02ff">&lt;<span style="font-weight:700">mrk</span> <span style="font-style:italic">mtype</span>=<span style="color:#d80800">"protected"</span>></span>Classicus scriptor non proletarius<span style="color:#1c02ff">&lt;/<span style="font-weight:700">mrk</span>></span>
        ('A distinguished not a commonplace writer'). 
    <span style="color:#1c02ff">&lt;/<span style="font-weight:700">source</span>></span>
    <span style="color:#1c02ff">&lt;<span style="font-weight:700">alt-trans</span> <span class="highlight"><span style="font-style:italic">match-quality</span>=<span style="color:#d80800">"0.749"</span></span> <span class="highlight"><span style="font-style:italic">origin</span>=<span style="color:#d80800">"MT"</span></span>></span>
        <span style="color:#1c02ff">&lt;<span style="font-weight:700">target</span> <span style="font-style:italic">xml</span>:lang=<span style="color:#d80800">"Spanish"</span> <span style="font-style:italic">its</span>:provenanceRecordsRef=<span style="color:#d80800">"#pr3"</span>></span>
            La primera 'Classic' Writer era aulus gellius un 2nd-century Roman Writer 
            que en la miscellany noctes atticae (19 8 15) refers a una Writer como un
            <span style="color:#1c02ff">&lt;<span style="font-weight:700">mrk</span> <span style="font-style:italic">mtype</span>=<span style="color:#d80800">"protected"</span>></span>Classicus scriptor non proletarius<span style="color:#1c02ff">&lt;/<span style="font-weight:700">mrk</span>></span>
            ('un Distinguished no una moneda corriente Writer').
        <span style="color:#1c02ff">&lt;/<span style="font-weight:700">target</span>></span>
    <span style="color:#1c02ff">&lt;/<span style="font-weight:700">alt-trans</span>></span>
<span style="color:#1c02ff">&lt;/<span style="font-weight:700">trans-unit</span>></span>
</pre>
</div>
                
                    <br/>&nbsp;<br/>
                    <b>Provenance record (output)</b>

<div class="span10">
<pre style="background:#fff;color:#000">style="color:#1c02ff">&lt;<span style="font-weight:700">xliff</span>></span>
    <span style="color:#1c02ff">&lt;<span style="font-weight:700">file</span>></span>
        <span style="color:#1c02ff">&lt;<span style="font-weight:700">header</span>></span>
            <span style="color:#1c02ff">&lt;<span style="font-weight:700">its</span><span style="font-weight:700">:</span><span style="font-weight:700">provenanceRecords</span> <span style="font-style:italic">xml</span>:id=<span style="color:#d80800">"pr1"</span>></span>
                <span style="color:#1c02ff">&lt;<span style="font-weight:700">its</span><span style="font-weight:700">:</span><span style="font-weight:700">provenanceRecord</span> <span style="font-style:italic">provRef</span>=<span style="color:#d80800">"http://www.cngl.ie/logger/logs/3f37155d-6f01-4abd-a7c0-87d64fc9f0fa"</span> /></span>
            <span style="color:#1c02ff">&lt;/<span style="font-weight:700">its</span><span style="font-weight:700">:</span><span style="font-weight:700">provenanceRecords</span>></span>
            <span style="color:#1c02ff">&lt;<span style="font-weight:700">its</span><span style="font-weight:700">:</span><span style="font-weight:700">provenanceRecords</span> <span style="font-style:italic">xml</span>:id=<span style="color:#d80800">"pr2"</span>></span>
                <span style="color:#1c02ff">&lt;<span style="font-weight:700">its</span><span style="font-weight:700">:</span><span style="font-weight:700">provenanceRecord</span> <span style="font-style:italic">provRef</span>=<span style="color:#d80800">"http://www.cngl.ie/logger/logs/501bae14-3b8d-4b15-875e-7c442f2e1b1e"</span> /></span>
            <span style="color:#1c02ff">&lt;/<span style="font-weight:700">its</span><span style="font-weight:700">:</span><span style="font-weight:700">provenanceRecords</span>></span>
            <span class="highlight"><span style="color:#1c02ff">&lt;<span style="font-weight:700">its</span><span style="font-weight:700">:</span><span style="font-weight:700">provenanceRecords</span> <span style="font-style:italic">xml</span>:id=<span style="color:#d80800">"pr3"</span>></span>
                <span style="color:#1c02ff">&lt;<span style="font-weight:700">its</span><span style="font-weight:700">:</span><span style="font-weight:700">provenanceRecord</span> <span style="font-style:italic">its</span>:tool=<span style="color:#d80800">"mosesmt"</span> <span style="font-style:italic">its</span>:orgRef=<span style="color:#d80800">"http://www.moravia.com"</span> <span style="font-style:italic">its</span>:provRef=<span style="color:#d80800">""</span> /></span>
            <span style="color:#1c02ff">&lt;/<span style="font-weight:700">its</span><span style="font-weight:700">:</span><span style="font-weight:700">provenanceRecords</span>></span></span>
            .
            .
            .
<span style="color:#1c02ff">&lt;<span style="font-weight:700">trans-unit</span> <span style="font-style:italic">id</span>=<span style="color:#d80800">"#4"</span>></span>
    <span style="color:#1c02ff">&lt;<span style="font-weight:700">source</span> <span style="font-style:italic">xml</span>:lang=<span style="color:#d80800">"English"</span>></span>
        The first 'Classic' writer was Aulus Gellius a 2nd-century Roman writer 
        who in the miscellany Noctes Atticae (19 8 15) refers to a writer as 
        a <span style="color:#1c02ff">&lt;<span style="font-weight:700">mrk</span> <span style="font-style:italic">mtype</span>=<span style="color:#d80800">"protected"</span>></span>Classicus scriptor non proletarius<span style="color:#1c02ff">&lt;/<span style="font-weight:700">mrk</span>></span>
        ('A distinguished not a commonplace writer'). 
    <span style="color:#1c02ff">&lt;/<span style="font-weight:700">source</span>></span>
    <span style="color:#1c02ff">&lt;<span style="font-weight:700">alt-trans</span> <span style="font-style:italic">match-quality</span>=<span style="color:#d80800">"0.749"</span> <span style="font-style:italic">origin</span>=<span style="color:#d80800">"MT"</span>></span>
        <span style="color:#1c02ff">&lt;<span style="font-weight:700">target</span> <span style="font-style:italic">xml</span>:lang=<span style="color:#d80800">"Spanish"</span> <span class="highlight"><span style="font-style:italic">its</span>:provenanceRecordsRef=<span style="color:#d80800">"#pr3"</span></span>></span>
            La primera 'Classic' Writer era aulus gellius un 2nd-century Roman Writer 
            que en la miscellany noctes atticae (19 8 15) refers a una Writer como un
            <span style="color:#1c02ff">&lt;<span style="font-weight:700">mrk</span> <span style="font-style:italic">mtype</span>=<span style="color:#d80800">"protected"</span>></span>Classicus scriptor non proletarius<span style="color:#1c02ff">&lt;/<span style="font-weight:700">mrk</span>></span>
            ('un Distinguished no una moneda corriente Writer').
        <span style="color:#1c02ff">&lt;/<span style="font-weight:700">target</span>></span>
    <span style="color:#1c02ff">&lt;/<span style="font-weight:700">alt-trans</span>></span>
<span style="color:#1c02ff">&lt;/<span style="font-weight:700">trans-unit</span>></span>
</pre>
</div>
                
                </li>
            
            </ul>
        
        </div>
    </div>


<!--#include file="Footer.htm"-->

</div>

</body>
</html>
