//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.586
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.586.
// 
#pragma warning disable 1591

namespace mlwlt_web_test.mlwlt_service {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="mlwlt_serviceSoap", Namespace="http://mlwlt.moravia.com/")]
    public partial class mlwlt_service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback mlwlt_xliff_mt_echoOperationCompleted;
        
        private System.Threading.SendOrPostCallback mlwlt_xliff_mt_prepareOperationCompleted;
        
        private System.Threading.SendOrPostCallback mlwlt_web_service_informationOperationCompleted;
        
        private System.Threading.SendOrPostCallback mlwlt_job_listOperationCompleted;
        
        private System.Threading.SendOrPostCallback mlwlt_job_logOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public mlwlt_service() {
            this.Url = global::mlwlt_web_test.Properties.Settings.Default.mlwlt_web_test_mlwlt_service_mlwlt_service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event mlwlt_xliff_mt_echoCompletedEventHandler mlwlt_xliff_mt_echoCompleted;
        
        /// <remarks/>
        public event mlwlt_xliff_mt_prepareCompletedEventHandler mlwlt_xliff_mt_prepareCompleted;
        
        /// <remarks/>
        public event mlwlt_web_service_informationCompletedEventHandler mlwlt_web_service_informationCompleted;
        
        /// <remarks/>
        public event mlwlt_job_listCompletedEventHandler mlwlt_job_listCompleted;
        
        /// <remarks/>
        public event mlwlt_job_logCompletedEventHandler mlwlt_job_logCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://mlwlt.moravia.com/mlwlt_xliff_mt_echo", RequestNamespace="http://mlwlt.moravia.com/", ResponseNamespace="http://mlwlt.moravia.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] mlwlt_xliff_mt_echo([System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] xliff_input, string fileName) {
            object[] results = this.Invoke("mlwlt_xliff_mt_echo", new object[] {
                        xliff_input,
                        fileName});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void mlwlt_xliff_mt_echoAsync(byte[] xliff_input, string fileName) {
            this.mlwlt_xliff_mt_echoAsync(xliff_input, fileName, null);
        }
        
        /// <remarks/>
        public void mlwlt_xliff_mt_echoAsync(byte[] xliff_input, string fileName, object userState) {
            if ((this.mlwlt_xliff_mt_echoOperationCompleted == null)) {
                this.mlwlt_xliff_mt_echoOperationCompleted = new System.Threading.SendOrPostCallback(this.Onmlwlt_xliff_mt_echoOperationCompleted);
            }
            this.InvokeAsync("mlwlt_xliff_mt_echo", new object[] {
                        xliff_input,
                        fileName}, this.mlwlt_xliff_mt_echoOperationCompleted, userState);
        }
        
        private void Onmlwlt_xliff_mt_echoOperationCompleted(object arg) {
            if ((this.mlwlt_xliff_mt_echoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.mlwlt_xliff_mt_echoCompleted(this, new mlwlt_xliff_mt_echoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://mlwlt.moravia.com/mlwlt_xliff_mt_prepare", RequestNamespace="http://mlwlt.moravia.com/", ResponseNamespace="http://mlwlt.moravia.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] mlwlt_xliff_mt_prepare([System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] xliff_input, string xliff_input_file_name) {
            object[] results = this.Invoke("mlwlt_xliff_mt_prepare", new object[] {
                        xliff_input,
                        xliff_input_file_name});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void mlwlt_xliff_mt_prepareAsync(byte[] xliff_input, string xliff_input_file_name) {
            this.mlwlt_xliff_mt_prepareAsync(xliff_input, xliff_input_file_name, null);
        }
        
        /// <remarks/>
        public void mlwlt_xliff_mt_prepareAsync(byte[] xliff_input, string xliff_input_file_name, object userState) {
            if ((this.mlwlt_xliff_mt_prepareOperationCompleted == null)) {
                this.mlwlt_xliff_mt_prepareOperationCompleted = new System.Threading.SendOrPostCallback(this.Onmlwlt_xliff_mt_prepareOperationCompleted);
            }
            this.InvokeAsync("mlwlt_xliff_mt_prepare", new object[] {
                        xliff_input,
                        xliff_input_file_name}, this.mlwlt_xliff_mt_prepareOperationCompleted, userState);
        }
        
        private void Onmlwlt_xliff_mt_prepareOperationCompleted(object arg) {
            if ((this.mlwlt_xliff_mt_prepareCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.mlwlt_xliff_mt_prepareCompleted(this, new mlwlt_xliff_mt_prepareCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://mlwlt.moravia.com/mlwlt_web_service_information", RequestNamespace="http://mlwlt.moravia.com/", ResponseNamespace="http://mlwlt.moravia.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode mlwlt_web_service_information() {
            object[] results = this.Invoke("mlwlt_web_service_information", new object[0]);
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void mlwlt_web_service_informationAsync() {
            this.mlwlt_web_service_informationAsync(null);
        }
        
        /// <remarks/>
        public void mlwlt_web_service_informationAsync(object userState) {
            if ((this.mlwlt_web_service_informationOperationCompleted == null)) {
                this.mlwlt_web_service_informationOperationCompleted = new System.Threading.SendOrPostCallback(this.Onmlwlt_web_service_informationOperationCompleted);
            }
            this.InvokeAsync("mlwlt_web_service_information", new object[0], this.mlwlt_web_service_informationOperationCompleted, userState);
        }
        
        private void Onmlwlt_web_service_informationOperationCompleted(object arg) {
            if ((this.mlwlt_web_service_informationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.mlwlt_web_service_informationCompleted(this, new mlwlt_web_service_informationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://mlwlt.moravia.com/mlwlt_job_list", RequestNamespace="http://mlwlt.moravia.com/", ResponseNamespace="http://mlwlt.moravia.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode mlwlt_job_list() {
            object[] results = this.Invoke("mlwlt_job_list", new object[0]);
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void mlwlt_job_listAsync() {
            this.mlwlt_job_listAsync(null);
        }
        
        /// <remarks/>
        public void mlwlt_job_listAsync(object userState) {
            if ((this.mlwlt_job_listOperationCompleted == null)) {
                this.mlwlt_job_listOperationCompleted = new System.Threading.SendOrPostCallback(this.Onmlwlt_job_listOperationCompleted);
            }
            this.InvokeAsync("mlwlt_job_list", new object[0], this.mlwlt_job_listOperationCompleted, userState);
        }
        
        private void Onmlwlt_job_listOperationCompleted(object arg) {
            if ((this.mlwlt_job_listCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.mlwlt_job_listCompleted(this, new mlwlt_job_listCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://mlwlt.moravia.com/mlwlt_job_log", RequestNamespace="http://mlwlt.moravia.com/", ResponseNamespace="http://mlwlt.moravia.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode mlwlt_job_log(string job) {
            object[] results = this.Invoke("mlwlt_job_log", new object[] {
                        job});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void mlwlt_job_logAsync(string job) {
            this.mlwlt_job_logAsync(job, null);
        }
        
        /// <remarks/>
        public void mlwlt_job_logAsync(string job, object userState) {
            if ((this.mlwlt_job_logOperationCompleted == null)) {
                this.mlwlt_job_logOperationCompleted = new System.Threading.SendOrPostCallback(this.Onmlwlt_job_logOperationCompleted);
            }
            this.InvokeAsync("mlwlt_job_log", new object[] {
                        job}, this.mlwlt_job_logOperationCompleted, userState);
        }
        
        private void Onmlwlt_job_logOperationCompleted(object arg) {
            if ((this.mlwlt_job_logCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.mlwlt_job_logCompleted(this, new mlwlt_job_logCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void mlwlt_xliff_mt_echoCompletedEventHandler(object sender, mlwlt_xliff_mt_echoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class mlwlt_xliff_mt_echoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal mlwlt_xliff_mt_echoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void mlwlt_xliff_mt_prepareCompletedEventHandler(object sender, mlwlt_xliff_mt_prepareCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class mlwlt_xliff_mt_prepareCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal mlwlt_xliff_mt_prepareCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void mlwlt_web_service_informationCompletedEventHandler(object sender, mlwlt_web_service_informationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class mlwlt_web_service_informationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal mlwlt_web_service_informationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void mlwlt_job_listCompletedEventHandler(object sender, mlwlt_job_listCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class mlwlt_job_listCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal mlwlt_job_listCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void mlwlt_job_logCompletedEventHandler(object sender, mlwlt_job_logCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class mlwlt_job_logCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal mlwlt_job_logCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591